### ISSUE TITLE
Paper Suggestion

### ISSUE THREAD

**Issue by JinheonBaek** [FilippoMB/The-expressive-power-of-pooling-in-GNNs#1]
First of all, thank you for your amazing contribution!
I would like to suggest considering one of my work that studies the expressive power of graph pooling: https://arxiv.org/abs/2102.11533 (ICLR 2021), showing that the proposed pooling operation is as powerful as the 1-WL test, which seems relevant to your work.

**Comment by JinheonBaek** [comment]
Oh, I forgot that I already suggested my paper few months ago via SNS. 
I commented above as I recently had to revisit this paper and feel we have similar contributions to the graph community, while your work provides more focused and comprehensive contributions and results toward the expressiveness of graph pooling.
I enjoy reading your paper, and as you said previously, could you please refer to my paper if you think mine is relevant? :)

**Comment by FilippoMB** [comment]
Hi Jinheon. We read your paper: it is indeed relevant and is already cited in our latest draft.
Our paper is currently under review and we are making some changes. Soon we will publish a new version on Arxiv, which will also contain a citation to your work.
